name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

     

      - run: flutter pub get

      - run: flutter test

      - run: flutter build apk --debug
